
  server:
    port: 4000

  spring:
    cloud:
      gateway:
        routes:
          - id: auth-service-route
            uri: http://nimbus-auth-service:4001
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1

          - id: customer-service-route
            uri: http://nimbus-customer-service:4002
            predicates:
              - Path=/api/customers/**
            filters:
              - StripPrefix=1
              - JwtValidation

          - id: order-service-route
            uri: http://nimbus-order-service:4003
            predicates:
              - Path=/api/orders/**
            filters:
              - StripPrefix=1
              - JwtValidation
